services:
  mt5-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: mt5-api:1
    ports:
      - "127.0.0.1:80:8000"
      - "127.0.0.1:5900:5900"
    environment:
#      VNC_USER: ${VNC_USER:-mt5_user}
      VNC_PASSWORD: ${VNC_PASSWORD:-p}
#      MT5_ACCOUNT_NUMBER: ${MT5_ACCOUNT_NUMBER}
#     MT5_API_PORT: ${MT5_API_PORT:-8000}
      API_KEY_SEED: ${API_KEY_SEED}
#      MT5_PASSWORD: ${MT5_PASSWORD}
#      MT5_SERVER: ${MT5_SERVER}
    env_file:
      - path: ./api/.env
        required: false
    volumes:
      - ./api:/root/api
      - ./data:/root/data
      - ./log:/root/log
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined

